BoxLayoutExample:


<BoxLayoutExample>:
    orentataion:"vertical" 
    Button:
        text:"A"
        size:"100dp","200dp"
        size_hint: None,None
    Button:
        text:"B"
    Label:
        text:"C"

<MainWidget>:
    Button:
        text:"Hello"
        size: "40dp","40dp"
        pos: "100dp","200dp"
        colour:0,0,1,1
    Label:
        text:"Hello2"
        size: "100dp" ,"80dp"
        pos: "200dp" , "300dp"
        colour: 1,0,0,1